version: "3"

services:
  vue_app:
    container_name: training_vue3

    environment:
      - NODE_ENV=development

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./vue_app/:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro

    ports:
      - 8000:8000
      - 3000:3000
      - 5173:5173 # viteのデフォルトポート

    command: bash -c "cd test && npm run dev"

    stdin_open: true
    tty: true
